image: Visual Studio 2019


install:
  - choco install gitversion.portable -y --version 5.12.0

before_build:
  - nuget restore
  - ps: gitversion /l console /output buildserver
  - ps: build\UpdateVersion.ps1

after_build:
  # Create Tapeti.Cmd release
  - cmd: dotnet publish -c Release -r win-x64 --self-contained=true -o publish\x64\selfcontained Tapeti.Cmd\Tapeti.Cmd.csproj
  - cmd: dotnet publish -c Release -r win-x64 --self-contained=false -o publish\x64 Tapeti.Cmd\Tapeti.Cmd.csproj
  - cmd: copy publish\x64\selfcontained\Tapeti.Cmd.exe publish\x64
  - cmd: rmdir /s /q publish\x64\selfcontained
  - cmd: 7z a output\Tapeti.Cmd-x64-%GitVersion_NuGetVersion%.zip %APPVEYOR_BUILD_FOLDER%\publish\x64\*
  # Push artifacts
  - ps: Get-ChildItem output\*.zip | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }

build:
  project: Tapeti.Cmd.sln

platform:
  - Any CPU

configuration:
  - Release

deploy:
  - provider: GitHub
    auth_token:
      secure: dWOConKg3VTPvd9DmWOOKiX1SJCalaqKInuk9GlKQOZX2s+Bia49J7q+AHO8wFj7
    artifact: /Tapeti.Cmd-.*\.zip/
    draft: false
    prerelease: false
    on:
      APPVEYOR_REPO_TAG: true